name = "medium-server"
main = "src/index.ts"
compatibility_date = "2025-01-25"


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODU4YzkzZmYtMmM3OC00OWMxLWJiMjctNTMxNmIyNGNlNmNjIiwidGVuYW50X2lkIjoiMmY3MGRmNDE1MTY4NjFiYWViNGYwMjk5Yjk2OTc0NTlkNTIzYzUxZjQ3NWY4OTJmMDkzMDIzYWI1NjBlYTBhOCIsImludGVybmFsX3NlY3JldCI6IjRjZWU3ZTVmLWJkMGItNDZlNC1iMzU5LWI0MTlhZWI1MWQwNiJ9.ztW3SRDTfZ7vayYySMSe56j60-ZcEU81i6hEmAAnQ90"
